### ISSUE TITLE
Mark all render steps as "processing" at once

### ISSUE THREAD

**Issue by aleclarson** [Popmotion/framesync#2]
Currently, if you call `onFrameRender` while the `onFrameStart` or `onFrameUpdate` steps are being processed, your callback (perhaps unexpectedly) is called synchronously. I believe that behavior should be opt-in (by setting the `immediate` argument to true).

As the current implementation stands, setting `immediate` to true during that time currently changes nothing. It's only when you call `onFrameRender` from within an `onFrameRender` callback that `immediate` changes the behavior from asynchronous to synchronous. Considering there's no way to explicitly check if the `onFrameRender` step is currently processing, I suggest the default behavior to be made **always** asynchronous.

Here's an example:
```js
// Add callback to update queue, process on next frame
onFrameUpdate(() => {
  // Add callback to render queue, process on next frame
  onFrameRender(() => {
    // With current behavior, this is called on current frame
  })
})

// Add callback to update queue, process ASAP (either current frame or next frame)
onFrameUpdate(() => {
  // Add callback to render queue, process on current frame
  onFrameRender(() => {
    // With current behavior, passing `true` changes nothing
  }, true)
}, true)
```

**Edit:** Almost forgot to clarify on the issue title! To accomplish the change to `immediate`, we could mark all render steps as "processing" at the beginning of each frame (before any render steps are processed). Doing so will gather the queued callbacks and clear the queue for next frame, which would effectively change the behavior of `immediate`.

WDYT @InventingWithMonster?

**Comment by aleclarson** [comment]
An important distinction I should make: by "synchronous", I mean "in the current frame", since technically the callback is queued and then executed after any earlier render steps and earlier queued callbacks of the same render step. By "asynchronous", I mean "in the next frame" of course.

**Comment by aleclarson** [comment]
If you're looking for a specific use case, let's say I want to queue both an `onFrameStart` callback and an `onFrameRender` callback, but the current render step is `onFrameUpdate`. There is currently no way to ensure my `onFrameRender` callback occurs after `onFrameStart` without embedding it into the `onFrameStart` callback. This is especially annoying when trying to interoperate between libraries that all use framesync.

**Comment by aleclarson** [comment]
I've rewritten this library with a new API and the concept described in this issue.

See here: https://github.com/aleclarson/framesync

**Comment by InventingWithMonster** [comment]
The use case I had for the library was scheduling a render for the same frame after performing an update.

It still mirrors the functionality of rAF where if, during a step, you call the same step, it by default fires on the following frame. 

The immediate flag is or should be undocumented, so it isn’t an official API. It could be just as easily accomplished with a new function that fires at the end of whichever step is currently being processed.
